In [12]:
import pandas as pd

soccer_data = {
    'Player Name': [
        'Lionel Messi', 'Cristiano Ronaldo', 'Neymar Jr', 'Kylian Mbappe', 'Kevin De Bruyne',
        'Mohamed Salah', 'Robert Lewandowski', 'Karim Benzema', 'Luka Modric', 'Erling Haaland'
    ],
    'Player Number': [10, 7, 11, 9, 17, 12, 8, 19, 3, 2],
    'Position': [
        'Forward', 'Forward', 'Forward', 'Forward', 'Midfielder',
        'Forward', 'Forward', 'Forward', 'Forward', 'Forward'
    ],
    'Club': [
        'Inter Miami', 'Al Nassr', 'Al Hilal', 'PSG', 'Manchester City',
        'Liverpool', 'Barcelona', 'Real Madrid', 'Real Madrid', 'Manchester City'
    ],
    'Goals': [30, 25, 20, 35, 15, 28, 33, 27, 10, 40],
    'Assists': [12, 10, 18, 15, 20, 14, 9, 11, 22, 8]
}

soccer_df = pd.DataFrame(soccer_data)
soccer_df.index = soccer_df["Player Number"]
soccer_df.index.name = None # Remove the index name for cleaner output

In [13]:
df_at = soccer_df.copy() # Work on a copy to keep original unchanged
print("Original Club for Player 17:", df_at.at[17, "Club"])
df_at.at[17, "Club"] = "White Angels"
print("New Club for Player 17 (using .at):", df_at.at[17, "Club"])

Original Club for Player 17: Manchester City
New Club for Player 17 (using .at): White Angels

In [14]:
df_loc_single = soccer_df.copy()
df_loc_single.loc[17, "Club"] = "Black Knights"
print("\nNew Club for Player 17 (using .loc single):", df_loc_single.loc[17, "Club"])

New Club for Player 17 (using .loc single): Black Knights

In [18]:
df_loc_multi_col = soccer_df.copy()
df_loc_multi_col.loc[17, ["Club", "Position"]] = ["Azure Dragons", "Defender"]
print("\nPlayer 17 after multiple column update (using .loc):\n", df_loc_multi_col.loc[17, ["Club", "Position"]])

df_loc_multi_col.loc[9, ["Goals", "Assists"]] = [12, 14]
df_loc_multi_col

Player 17 after multiple column update (using .loc):
 Club        Azure Dragons
Position         Defender
Name: 17, dtype: object

,Player Name,Player Number,Position,Club,Goals,Assists
10,Lionel Messi,10,Forward,Inter Miami,30,12
7,Cristiano Ronaldo,7,Forward,Al Nassr,25,10
11,Neymar Jr,11,Forward,Al Hilal,20,18
9,Kylian Mbappe,9,Forward,PSG,12,14
17,Kevin De Bruyne,17,Defender,Azure Dragons,15,20
12,Mohamed Salah,12,Forward,Liverpool,28,14
8,Robert Lewandowski,8,Forward,Barcelona,33,9
19,Karim Benzema,19,Forward,Real Madrid,27,11
3,Luka Modric,3,Forward,Real Madrid,10,22
2,Erling Haaland,2,Forward,Manchester City,40,8

In [25]:
df_loc_multi_row = soccer_df.copy()
# Change position for players 10 and 7
df_loc_multi_row.loc[[10, 7], "Position"] = "Midfielder"
print("\nPlayers 10 & 7 after position update (using .loc):\n", df_loc_multi_row.loc[[10, 7], "Position"])

df_loc_multi_row.loc[[12, 19], "Position"] = "Attacker"

df_loc_multi_row.loc[[10, 3], "Goals"] = [38, 37]
df_loc_multi_row

Players 10 & 7 after position update (using .loc):
 10    Midfielder
7     Midfielder
Name: Position, dtype: object

,Player Name,Player Number,Position,Club,Goals,Assists
10,Lionel Messi,10,Midfielder,Inter Miami,38,12
7,Cristiano Ronaldo,7,Midfielder,Al Nassr,25,10
11,Neymar Jr,11,Forward,Al Hilal,20,18
9,Kylian Mbappe,9,Forward,PSG,35,15
17,Kevin De Bruyne,17,Midfielder,Manchester City,15,20
12,Mohamed Salah,12,Attacker,Liverpool,28,14
8,Robert Lewandowski,8,Forward,Barcelona,33,9
19,Karim Benzema,19,Attacker,Real Madrid,27,11
3,Luka Modric,3,Forward,Real Madrid,37,22
2,Erling Haaland,2,Forward,Manchester City,40,8